#!/usr/bin/env -S PYTHONPATH=../../../tools/extract-utils python3
#
# SPDX-FileCopyrightText: 2024 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

from extract_utils.file import File
from extract_utils.fixups_blob import (
    blob_fixup,
    blob_fixups_user_type,
)
from extract_utils.fixups_lib import (
    lib_fixup_remove,
    lib_fixups,
    lib_fixups_user_type,
)
from extract_utils.main import (
    ExtractUtils,
    ExtractUtilsModule,
)

namespace_imports = [
    'device/sony/sphinx',
    'hardware/qcom-caf/sm8150',
    'hardware/qcom-caf/wlan',
    'hardware/sony',
    'vendor/qcom/opensource/commonsys/display',
    'vendor/qcom/opensource/commonsys-intf/display',
    'vendor/qcom/opensource/dataservices',
    'vendor/qcom/opensource/display',
]

blob_fixups: blob_fixups_user_type = {
(
        'system/lib/com.qualcomm.qti.ant@1.0.so',
        'system/lib/com.qualcomm.qti.dpm.api@1.0.so',
        'system/lib/vendor.qti.hardware.tui_comm@1.0.so',
        'system/lib64/com.qualcomm.qti.ant@1.0.so',
        'system/lib64/com.qualcomm.qti.dpm.api@1.0.so',
        'system/lib64/com.qualcomm.qti.imscmservice@1.0.so',
        'system/lib64/com.qualcomm.qti.imscmservice@2.0.so',
        'system/lib64/com.qualcomm.qti.imscmservice@2.1.so',
        'system/lib64/com.qualcomm.qti.uceservice@2.0.so',
        'system/lib64/com.quicinc.cne.server@1.0.so',
        'system/lib64/vendor.qti.hardware.tui_comm@1.0.so',
        'system/lib64/vendor.qti.ims.callinfo@1.0.so',
        'system/lib64/vendor.qti.ims.rcsconfig@1.0.so',
        'vendor/bin/cnd',
        'vendor/bin/dpmQmiMgr',
        'vendor/bin/hw/vendor.display.color@1.0-service',
        'vendor/bin/hw/vendor.semc.hardware.charger@1.0-service',
        'vendor/bin/hw/vendor.semc.hardware.secd@1.0-service',
        'vendor/bin/hw/vendor.somc.hardware.miscta@1.0-service',
        'vendor/bin/ims_rtp_daemon',
        'vendor/bin/vppservice',
        'vendor/lib/com.qualcomm.qti.dpm.api@1.0.so',
        'vendor/lib/com.quicinc.cne.api@1.0.so',
        'vendor/lib/com.quicinc.cne.api@1.1.so',
        'vendor/lib/com.quicinc.cne.server@2.0.so',
        'vendor/lib/com.quicinc.cne.server@2.1.so',
        'vendor/lib/com.quicinc.cne.server@2.2.so',
        'vendor/lib/com.quicinc.cne.server@2.3.so',
        'vendor/lib/vendor.qti.data.factory@1.0.so',
        'vendor/lib/vendor.qti.data.factory@1.1.so',
        'vendor/lib/vendor.qti.hardware.data.connection@1.0.so',
        'vendor/lib/vendor.qti.hardware.data.dynamicdds@1.0.so',
        'vendor/lib/vendor.qti.hardware.data.latency@1.0.so',
        'vendor/lib/vendor.qti.hardware.data.qmi@1.0.so',
        'vendor/lib/vendor.qti.hardware.fm@1.0.so',
        'vendor/lib/vendor.qti.hardware.qteeconnector@1.0.so',
        'vendor/lib/vendor.qti.hardware.soter@1.0.so',
        'vendor/lib/vendor.qti.hardware.tui_comm@1.0.so',
        'vendor/lib/vendor.qti.hardware.vpp@1.1.so',
        'vendor/lib/vendor.qti.hardware.vpp@1.2.so',
        'vendor/lib/vendor.qti.ims.rcsconfig@1.0.so',
        'vendor/lib/vendor.qti.latency@2.0.so',
        'vendor/lib/vendor.semc.hardware.light@1.0.so',
        'vendor/lib/vendor.somc.hardware.camera.cacao@1.0.so',
        'vendor/lib/vendor.somc.hardware.camera.cacao@2.0.so',
        'vendor/lib/vendor.somc.hardware.camera.cacao@3.0.so',
        'vendor/lib/vendor.somc.hardware.camera.cacao@3.1.so',
        'vendor/lib/vendor.somc.hardware.camera.cacao@3.2.so',
        'vendor/lib/vendor.somc.hardware.camera.device@1.0.so',
        'vendor/lib/vendor.somc.hardware.miscta@1.0.so',
        'vendor/lib/vendor.somc.hardware.security.secd@1.0.so',
        'vendor/lib/vendor.somc.hardware.swiqi@1.0.so',
        'vendor/lib64/com.qualcomm.qti.dpm.api@1.0.so',
        'vendor/lib64/com.qualcomm.qti.imscmservice@1.0.so',
        'vendor/lib64/com.qualcomm.qti.imscmservice@2.0.so',
        'vendor/lib64/com.qualcomm.qti.imscmservice@2.1.so',
        'vendor/lib64/com.qualcomm.qti.uceservice@2.0.so',
        'vendor/lib64/com.quicinc.cne.api@1.0.so',
        'vendor/lib64/com.quicinc.cne.api@1.1.so',
        'vendor/lib64/com.quicinc.cne.server@2.0.so',
        'vendor/lib64/com.quicinc.cne.server@2.1.so',
        'vendor/lib64/com.quicinc.cne.server@2.2.so',
        'vendor/lib64/com.quicinc.cne.server@2.3.so',
        'vendor/lib64/vendor.display.color@1.0.so',
        'vendor/lib64/vendor.display.color@1.1.so',
        'vendor/lib64/vendor.display.color@1.2.so',
        'vendor/lib64/vendor.display.postproc@1.0.so',
        'vendor/lib64/vendor.qti.data.factory@1.0.so',
        'vendor/lib64/vendor.qti.data.factory@1.1.so',
        'vendor/lib64/vendor.qti.gnss@1.0.so',
        'vendor/lib64/vendor.qti.gnss@1.1.so',
        'vendor/lib64/vendor.qti.gnss@1.2.so',
        'vendor/lib64/vendor.qti.gnss@2.0.so',
        'vendor/lib64/vendor.qti.gnss@2.1.so',
        'vendor/lib64/vendor.qti.hardware.cvp@1.0.so',
        'vendor/lib64/vendor.qti.hardware.data.connection@1.0.so',
        'vendor/lib64/vendor.qti.hardware.data.dynamicdds@1.0.so',
        'vendor/lib64/vendor.qti.hardware.data.latency@1.0.so',
        'vendor/lib64/vendor.qti.hardware.data.qmi@1.0.so',
        'vendor/lib64/vendor.qti.hardware.fm@1.0.so',
        'vendor/lib64/vendor.qti.hardware.qteeconnector@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.am@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.1.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.2.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.3.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.4.so',
        'vendor/lib64/vendor.qti.hardware.radio.ims@1.5.so',
        'vendor/lib64/vendor.qti.hardware.radio.lpa@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.qtiradio@2.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.qtiradio@2.1.so',
        'vendor/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.uim@1.0.so',
        'vendor/lib64/vendor.qti.hardware.radio.uim@1.1.so',
        'vendor/lib64/vendor.qti.hardware.sensorscalibrate@1.0.so',
        'vendor/lib64/vendor.qti.hardware.soter@1.0.so',
        'vendor/lib64/vendor.qti.hardware.tui_comm@1.0.so',
        'vendor/lib64/vendor.qti.hardware.vpp@1.1.so',
        'vendor/lib64/vendor.qti.hardware.vpp@1.2.so',
        'vendor/lib64/vendor.qti.ims.callinfo@1.0.so',
        'vendor/lib64/vendor.qti.ims.rcsconfig@1.0.so',
        'vendor/lib64/vendor.qti.imsrtpservice@1.0.so',
        'vendor/lib64/vendor.qti.latency@2.0.so',
        'vendor/lib64/vendor.semc.hardware.light@1.0.so',
        'vendor/lib64/vendor.semc.hardware.thermal@1.0.so',
        'vendor/lib64/vendor.somc.hardware.miscta@1.0.so',
        'vendor/lib64/vendor.somc.hardware.modemswitcher@1.0.so',
        'vendor/lib64/vendor.somc.hardware.radio@1.0.so',
        'vendor/lib64/vendor.somc.hardware.security.secd@1.0.so',
        'vendor/lib64/vendor.somc.hardware.swiqi@1.0.so',
        'vendor/lib64/vendor.qti.hardware.iop@1.0.so',
        'vendor/lib64/vendor.qti.hardware.iop@2.0.so',
        'vendor/lib/com.qualcomm.qti.ant@1.0.so',
        'vendor/lib64/com.qualcomm.qti.ant@1.0.so',
        'vendor/lib/vendor.qti.power.pasrmanager@1.0.so',
        'vendor/lib64/vendor.qti.power.pasrmanager@1.0.so',
    ): blob_fixup()
        .replace_needed('libhidlbase.so', 'libhidlbase-v32.so'),
    (
        'vendor/bin/thermal-engine',
        'vendor/bin/keyprovd',
        'vendor/bin/wvkbd',
        'vendor/bin/imsdatadaemon',
    ): blob_fixup()
        .add_needed('libhidlbase-v32.so'),
    (
        'vendor/lib/libgps.utils.so',
        'vendor/lib64/libgps.utils.so',
    ): blob_fixup()
        .add_needed('libprocessgroup.so'),
}

module = ExtractUtilsModule(
    'sphinx',
    'sony',
    blob_fixups=blob_fixups,
    namespace_imports=namespace_imports,
)

if __name__ == '__main__':
    utils = ExtractUtils.device(module)
    utils.run()